# Generated by SnowIaC for ticket RITM0654928 (rerun 20260509211456)
# Requested for: Amy, smith
# Description: We are in process of migrating oracle to SQL Server , orac1 to new VMs:   sql1.    We are facing performance issue due to Premium V2 supports 3000 IOPS and 125 mbps only.   Please increase the through
#
# This module MODIFIES an existing PremiumV2 managed disk to change its
# IOPS / throughput. It does NOT create a new disk. The Terraform `import`
# block (Terraform >= 1.5) attaches the live resource to state on first apply.
#
# Required tfvars (see terraform.auto.tfvars for ticket-derived defaults):
#   subscription_id, resource_group_name, disk_name, location, disk_size_gb,
#   storage_account_type

terraform {
  required_version = ">= 1.5"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  features {}
}

variable "subscription_id" { type = string }
variable "resource_group_name" { type = string }
variable "disk_name" { type = string }
variable "location" { type = string }
variable "disk_size_gb" { type = number }
variable "storage_account_type" {
  type    = string
  default = "PremiumV2_LRS"
}

# Attach the existing disk to Terraform state instead of creating a new one.
import {
  to = azurerm_managed_disk.sql1_data
  id = "/subscriptions/${var.subscription_id}/resourceGroups/${var.resource_group_name}/providers/Microsoft.Compute/disks/${var.disk_name}"
}

resource "azurerm_managed_disk" "sql1_data" {
  name                 = var.disk_name
  resource_group_name  = var.resource_group_name
  location             = var.location
  storage_account_type = var.storage_account_type
  create_option        = "Empty" # required field; ignored on import
  disk_size_gb         = var.disk_size_gb

  # The actual change requested by ticket RITM0654928:
  disk_iops_read_write = 5000
  disk_mbps_read_write = 350

  tags = {
    snow_ticket = "RITM0654928"
    managed_by  = "snowiac"
  }

  # Existing disks may be zonal; we never want to recreate the disk just
  # to change zone/size/sku — only IOPS and throughput are mutable here.
  lifecycle {
    ignore_changes = [create_option, disk_size_gb, storage_account_type, zone]
  }
}

output "disk_iops" {
  value = azurerm_managed_disk.sql1_data.disk_iops_read_write
}

output "disk_mbps" {
  value = azurerm_managed_disk.sql1_data.disk_mbps_read_write
}
