# Auto-generated by SnowIaC for ticket RITM0010004 — review before merge.
# Edit any UNKNOWN values to match the live Azure resource the ticket targets.
subscription_id      = "00000000-0000-0000-0000-000000000000"
resource_group_name  = "MultiAgentSnow"
disk_name            = "sql1-data"
location             = "eastus"
disk_size_gb         = 1024
storage_account_type = "PremiumV2_LRS"
