"""Code-generation agent: renders Terraform, opens a GitHub PR, alerts admin."""
from __future__ import annotations

import logging

from agent_framework import Agent

from ..llm import get_chat_client
from ..models import CodeGenResult, IntakeResult, RequestKind
from ..services import github_repo, parameter_extractor, servicenow, terraform_generator

log = logging.getLogger(__name__)

INSTRUCTIONS = """
You are the Code-Generation Agent. You receive a validated ServiceNow ticket
and a draft Terraform plan. Your job is to write the **PR description** for the
human reviewer.

The PR description must include:
1. Summary of the change in 1-2 sentences.
2. Linked ServiceNow ticket ID.
3. A bulleted list of resources being created or modified.
4. A "Reviewer checklist" section.

Keep it under 250 words. Plain Markdown. Do not invent fields the ticket does
not mention.
""".strip()


async def _draft_pr_body(intake: IntakeResult, files: dict[str, str]) -> str:
    file_list = "\n".join(f"- `{p}`" for p in files)
    fallback = (
        f"## Auto-generated by SnowIaC\n\n"
        f"ServiceNow ticket: **{intake.ticket_id}** ({intake.kind.value})\n\n"
        f"### Files\n{file_list}\n\n"
        f"### Reviewer checklist\n"
        f"- [ ] Terraform `plan` output reviewed\n"
        f"- [ ] Change matches business intent in the ticket\n"
        f"- [ ] No secrets in code\n"
    )
    try:
        client = get_chat_client()
        prompt = (
            f"Ticket: {intake.ticket.model_dump_json()}\n\n"
            f"Generated files:\n{file_list}\n\n"
            f"Write the PR description."
        )
        async with Agent(
            client=client, name="CodeGenAgent", instructions=INSTRUCTIONS
        ) as agent:
            response = await agent.run(prompt)
            return (response.text or fallback).strip()
    except Exception as e:  # noqa: BLE001
        log.warning("CodeGenAgent LLM call failed (%s) — using fallback PR body", e)
        return fallback


async def run(intake: IntakeResult) -> CodeGenResult:
    azure_params: dict | None = None
    verification_spec: dict | None = None
    if intake.kind is RequestKind.AZURE_INFRA_CHANGE:
        params = await parameter_extractor.extract_azure_disk_params(intake.ticket)
        azure_params = params.model_dump()
        log.info("Extracted Azure params for %s: %s", intake.ticket_id, azure_params)
        verification_spec = {
            "resource_type": "azurerm_managed_disk",
            "resource_group_name": params.resource_group_name,
            "resource_name": params.disk_name,
            "asserts": {
                "disk_iops_read_write": {"op": ">=", "value": params.target_iops},
                "disk_mbps_read_write": {"op": ">=", "value": params.target_mbps},
            },
        }

    files = terraform_generator.render(intake.ticket, intake.kind, azure_params=azure_params)
    body = await _draft_pr_body(intake, files)

    branch = f"snowiac/{intake.ticket_id.lower()}"
    title = f"[{intake.ticket_id}] {intake.ticket.ShortDescription or intake.kind.value}"

    gh = github_repo.build_client()
    pr = gh.open_pr(branch=branch, title=title, body=body, files=files)

    if verification_spec is not None:
        # Late import avoids circular dep (workflow imports agents.code_generation).
        from ..workflow import get_store

        get_store().put_spec(intake.ticket_id, verification_spec)
        log.info("Stored verification spec for %s: %s", intake.ticket_id, verification_spec)

    snow = servicenow.build_client()
    snow_ok = True
    try:
        await snow.add_comment(
            intake.ticket_id,
            f"[SnowIaC] Terraform generated and opened for review: {pr.url}. "
            f"A cloud admin will approve and merge to apply the change.",
        )
        await snow.update_state(intake.ticket_id, state="Work in Progress", stage="Awaiting Approval")
    except Exception as e:  # noqa: BLE001
        log.warning("ServiceNow update failed for %s (%s) — continuing", intake.ticket_id, e)
        snow_ok = False

    notes = (
        "PR opened and admin notified via ServiceNow comment."
        if snow_ok
        else "PR opened; ServiceNow notification failed (see server logs)."
    )
    return CodeGenResult(
        ticket_id=intake.ticket_id,
        pr_url=pr.url,
        pr_number=pr.number,
        branch=pr.branch,
        files=list(files),
        notes=notes,
    )
